default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 10000
  pool: <%= (ENV['DB_MAX_THREADS'] || 5).to_i * 2 %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>

development:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  user: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>


